# Generated by Django 3.0.2 on 2020-01-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('genre', models.IntegerField(choices=[(0, 'Comedy'), (1, 'Horror'), (2, 'Drama'), (3, 'Documentary'), (4, 'Action'), (5, 'Historic')])),
                ('rate', models.FloatField(default=0)),
                ('premiere_year', models.IntegerField()),
                ('country', models.CharField(max_length=2)),
                ('cast', models.ManyToManyField(to='people.Person')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='people.Person')),
                ('scenarist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarist', to='people.Person')),
            ],
        ),
    ]
