# Generated by Django 3.0.2 on 2020-01-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
