# Generated by Django 3.0.2 on 2020-01-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='premiere_year',
            new_name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Documentary', 'Documentary'), ('Action', 'Action'), ('Historic', 'Historic')]),
        ),
    ]
