# Generated by Django 3.0.2 on 2020-01-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200109_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Documentary', 'Documentary'), ('Action', 'Action'), ('Historic', 'Historic')], max_length=32),
        ),
    ]
