# Generated by Django 3.0.2 on 2020-01-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200109_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='scenarist',
            new_name='writer',
        ),
    ]
