# Generated by Django 3.0.2 on 2020-01-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200109_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Documentary', 'Documentary'), ('Action', 'Action'), ('Historic', 'Historic'), ('Thriller', 'Thriller')], max_length=32),
        ),
    ]
